### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by Neiasut** [iqstore/iqchannels-widget#2]
Добрый день! Ваш виджет вставляет в head родительской страницы инлайновый код репозитория normailze.css v5. Вы же используете iframe, внутри которого делаете то же самое (оправдано). Так как вы вставляете в родительскую страницу normailze - вы ломаете оформление у равновесовых стилей компонентов на сайте. Не могли бы вы убрать добавление normalize в тело самой страницы?

**Comment by ivankorobkov** [comment]
Да, можно, только это не так просто и не быстро. Может, на след неделе будет готово.

**Comment by ivankorobkov** [comment]
Готово в версии http://wiki.iqstore.ru/display/IQDOC/IQChannels+2019.1.9
